fragment GlobalParts on Global {
  __typename
  alertBanner {
    __typename
    alertLabel
    alertLink
    alertLinkText
  }
  navigation {
    __typename
    mainNav {
      __typename
      label
      href
      featuredCards {
        __typename
        image {
          __typename
          src
          alt
        }
        title
        description
        ctaText
        ctaLink
        layout
      }
      subItems {
        __typename
        label
        href
        icon
        variant
        description
      }
    }
    footer {
      __typename
      contact {
        __typename
        phone
        textNumber
        email
      }
      social {
        __typename
        platform
        url
      }
      companyName
    }
  }
}

fragment PageParts on Page {
  __typename
  title
  description
  template
  subtitle
  peopleType
  people {
    __typename
    id
    name
    title
    bio
    image {
      __typename
      src
      alt
    }
    contact {
      __typename
      email
      phone
      website
    }
    social {
      __typename
      linkedin
      twitter
      instagram
      facebook
    }
    specialties
    location
  }
  headerBlocks {
    __typename
    ... on PageHeaderBlocksHero {
      heading
      subheading
      buttonText
      buttonLink
      collageImages {
        __typename
        src
      }
    }
  }
  blocks {
    __typename
    ... on PageBlocksCtaBlock {
      heading
      subheading
      content
      buttonText
      buttonLink
      imageLeft
      imageSrc
      imageAlt
      backgroundColor
    }
    ... on PageBlocksHero {
      heading
      subheading
      buttonText
      buttonLink
      collageImages {
        __typename
        src
      }
    }
    ... on PageBlocksRichTextBlock {
      heading
      subheading
      features {
        __typename
        icon
        title
        description
      }
    }
    ... on PageBlocksCarouselBlock {
      blockTitle
      blockSubtitle
      slides {
        __typename
        src
        alt
        testimonialText
        clientName
        clientType
      }
      options_loop
      autoplayInterval
    }
    ... on PageBlocksServiceListingBlock {
      title
      services {
        __typename
        name
        slug
      }
      ctaText
      ctaLink
      ctaContent
      backgroundColor
    }
    ... on PageBlocksBannerBlock {
      title
      subtitle
      benefits {
        __typename
        icon
        heading
        text
        backgroundColor
        buttonText
        buttonLink
      }
    }
  }
}
